name: selenium-flask-app
services:
- name: web
  github:
    repo: <your-github-username>/<your-repo-name>
    branch: main
    deploy_on_push: true
  source_dir: /
  run_command: gunicorn --worker-tmp-dir /dev/shm --workers 2 --threads 4 --bind 0.0.0.0:$PORT app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  http_port: 5000